<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Automation Registration Page"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="0.633">
  <properties />
            <testcase name="homePageTitleTest" time="0.045" classname="com.testingproject.qa.testcases.AutomationPageTest">
                <failure type="java.lang.AssertionError"
                  message="null"
              >
<![CDATA[java.lang.AssertionError: null
  org.testng.Assert.fail(Assert.java:110)
  org.testng.Assert.fail(Assert.java:115)
  com.testingproject.qa.testcases.AutomationPageTest.homePageTitleTest(AutomationPageTest.java:38)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  java.base/java.lang.reflect.Method.invoke(Method.java:578)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:808)
  org.testng.TestRunner.run(TestRunner.java:603)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
  org.testng.SuiteRunner.run(SuiteRunner.java:326)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.runSuites(TestNG.java:1092)
  org.testng.TestNG.run(TestNG.java:1060)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
  org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
  org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="Submitclick" time="0.588" classname="com.testingproject.qa.testcases.AutomationPageTest" />
      
</testsuite>
